version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: "mongo:5.0.17"
    volumes:
      - yolomy:/data/db
    ports:
      - "27017:27017"
    networks:
      - ecomm-network
  backend:
    container_name: backend_yolo
    build: ./backend
    image: winniegitau/backend_yolo:1.0.0
    ports:
      - "5000:5000"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb/yolomy
    networks:
      - ecomm-network
  client:
    container_name: client_yolo
    build: ./client
    image: winniegitau/client_yolo:1.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - ecomm-network
networks:
  ecomm-network:
    driver: bridge
volumes:
  yolomy:
  logs:
