---
- name: yolo-ecommerce Playbook
  hosts: all
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: update apt cache
      apt: 
        update_cache: yes

  tasks:
    - name: Install git
      include_role:
        name: git

    - name: install docker and docker-compose
      include_role: 
        name: docker

    - name: run docker compose
      include_role:
        name: docker-compose
