apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: gcr.io/plasma-iterator-386208/backend:v1
        name: backend
        imagePullPolicy: Always
        env:
          - name: MONGODB_URI
            value: mongodb://mongodb:27017/yolomy
        resources: {}
        ports:
          - containerPort: 5000
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    run: backend
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: backend
  type: LoadBalancer